language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - mysql -e "create database IF NOT EXISTS test_db;" -uroot; fi
  - composer update

script: phpunit --configuration phpunit.xml --coverage-text